People/Controllers/UrlController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using DAL.FNhibernate.Entities;
using DAL.FNhibernate.Repositories;
using Logic.Services;
using Microsoft.Security.Application;
using Microsoft.Web.Helpers;
using People.Attributes;
using People.Models;
using System.Linq;
using People.Utility;

namespace People.Controllers
{
    public class UrlController : Controller
    {
        private IUrlRepository urlRepository;
        private IPostRepository postRepository;
        private readonly IUserRepository userRepository;
        private readonly ICommentsRepository commentsRepository;
        private readonly IHostHeaderService hostHeaderService;
        readonly string domainName = ConfigurationManager.AppSettings["DomanName"];
        readonly string privateKey = ConfigurationManager.AppSettings["RecaptchaPrivateKey"];
        readonly string websiteName = ConfigurationManager.AppSettings["SiteName"];

        public UrlController(IUrlRepository urlRepository, IPostRepository postRepository, IUserRepository userRepository,
            ICommentsRepository commentsRepository, IHostHeaderService hostHeaderService)
        {
            this.urlRepository = urlRepository;
            this.postRepository = postRepository;
            this.userRepository = userRepository;
            this.commentsRepository = commentsRepository;
            this.hostHeaderService = hostHeaderService;
        }

        public ActionResult Index(string id)
        {
            //todo: parse for special characters here 
            var url = urlRepository.GetUrlWithPost(id);

            if (url != null && url.Posts != null)
            {
                var posts = url.Posts;
                ViewBag.IsAdminOrOwner = posts.UserProfile.UserName == User.Identity.Name;
                ViewBag.Title = id;
                url.Hits++;
                ViewBag.Hits = url.Hits;
                return View(posts);
            }
            ViewBag.DomainName = domainName;
            return View("PageNotFound");
        }

        public ActionResult IframeBody(int id)
        {
            var posts = postRepository.GetPost(id);
            return View("Iframe", (object)posts.Body);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            return View(new PostsViewModel());
        }
        
        [ValidateInput(false)]
        [Authorize]
        [HttpPost]
        public ActionResult Create(PostsViewModel postsViewModel)
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            var isCaptchaValid = ReCaptcha.Validate(privateKey);
            if (ModelState.IsValid && isCaptchaValid)
            {
                UserProfile userProfile = userRepository.GetUser(User.Identity.Name);
                string subDomain = postsViewModel.Subdomain;
                var url = urlRepository.GetUrl(subDomain);
                if (url != null)
                {
                    ModelState.AddModelError("subDomainChosen", "Subdomain already taken, please choose another");
                    return View(postsViewModel);
                }
//                    var fullSubdomainWithPostfix = subDomain + "." + websiteName + ".com";
                var posts = new Posts
                    {
                        Body = HtmlUtility.Instance.SanitizeHtml(postsViewModel.Body),
                        Title = HtmlUtility.Instance.SanitizeHtml(postsViewModel.Title),
                        Samay = DateTime.UtcNow,
                        Commentable = postsViewModel.Commentable,
                        ShowHits = postsViewModel.ShowHits,
                        UserProfile = userProfile,
                        Url = subDomain
                    };
//                    hostHeaderService.AddHostHeader(websiteName, fullSubdomainWithPostfix);

                var urlMapping = new UrlMapping
                {
                    Url = subDomain,
                    Posts = posts
                };
                urlRepository.Save(urlMapping);
                return Redirect("http://" + subDomain + "." + domainName);    
            }
            return View(postsViewModel);
        }

        public JsonResult IsDomainFree(string Id)
        {
            if (string.IsNullOrEmpty(Id))
            {
                return null;
            }
            var urlMapping = urlRepository.GetUrl(Id);
            if (urlMapping == null)
            {
                return Json(new { isFree = true });
            }
            return Json(new { isFree = false });
        }

        [MyPostUserAuthorization]
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Posts post = postRepository.GetPost(id);
            UrlMapping urlWithPost = urlRepository.GetUrlWithPost(post);
            
//            string subDomain = urlWithPost.Url;

            urlRepository.Delete(urlWithPost);
            
//            var fullSubdomainWithPostfix = subDomain + "." + websiteName + ".com";
//            hostHeaderService.RemoveHostHeader(websiteName, fullSubdomainWithPostfix);

            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult DelteComment(int id)
        {
            Comments commentsWithPost = commentsRepository.GetCommentsWithPost(id);
            if (commentsWithPost == null)
            {
                return Json(new
                    {
                        IsSuccess = false,
                        Id = id,
                        Message = "Comment already deleted"
                    });
            }
            if (commentsWithPost.Posts.UserProfile.UserName == User.Identity.Name)
            {
                commentsRepository.Delete(commentsWithPost);
                return Json(new
                {
                    IsSuccess = true,
                    Id = id
                });    
            }
            return Json(new
                {
                    error = "You're not authorised to delete Comments"
                });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Comments(CommentsModel comments)
        {
            var isCaptchaValid = ReCaptcha.Validate(privateKey);
            if (ModelState.IsValid && isCaptchaValid)
            {
                Posts post = postRepository.GetPost(comments.PostId);
                if (post == null)
                {
                    return RedirectToAction("Index");
                }
                post.Comments.Add(new Comments
                {
                    Body = HtmlUtility.Instance.SanitizeHtml(comments.Body),
                    Email = comments.Email,
                    Name = comments.Name,
                    Samay = DateTime.UtcNow,
                    Posts = post
                });
                postRepository.Save(post);
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
            string errors = string.Join(@"<br \>", ModelState.Values
                                                        .SelectMany(x => x.Errors)
                                                        .Select(x => x.ErrorMessage));
            if (!isCaptchaValid)
            {
                errors = string.Join(@"<br \>",
                                 "The characters you entered donot match the one in image. Please try again ..");    
            }
            
            return Json(new
                {
                    errors
                });
        }

        [HttpGet]
        [MyPostUserAuthorization]
        public ActionResult Edit(int id)
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            Posts posts = postRepository.GetPost(id);
            if (posts!=null)
            {
                var postsViewModel = new PostsViewModel
                {
                    Body = posts.Body,
                    Id = posts.Id,
                    Commentable = posts.Commentable,
                    Subdomain = posts.Url,
                    Title = posts.Title
                };
                return View(postsViewModel);    
            }
            return View("AccessDenied");
        }

        [ValidateInput(false)]
        [MyPostUserAuthorization]
        [HttpPost]
        public ActionResult Edit(PostsViewModel postsModel)
        {
            if (ModelState.IsValid)
            {
                Posts post = postRepository.GetPost(postsModel.Id);
                string url = urlRepository.GetUrlForPost(post);
                //todo: plzz do some sql injection and spl characters checks ?? If you don't fix this and go to prod, you will be screwed ! SCREWED !
                post.Body = HtmlUtility.Instance.SanitizeHtml(postsModel.Body);
                post.Title = HtmlUtility.Instance.SanitizeHtml(postsModel.Title);
                post.Commentable = postsModel.Commentable;
                post.ShowHits = postsModel.ShowHits;
                postRepository.Save(post);

                return Redirect("http://" + url + "." + domainName);
            }
            return View(postsModel);
        }
    }
}

People/Views/Url/AccessDenied.cshtml
@model dynamic

@{
    ViewBag.Title = "Access Denied !";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="container ">
    <div class="hero-unit">
        <h4 class="text-center text-error">You donot have, permission to view this page, please Log-in using the appropriate account to edit </h4>        
    </div>
</div>

People/Views/Url/AddComment.cshtml
@using Microsoft.Web.Helpers
@model People.Models.CommentsModel
<div id="commentEditor">
    <div id="commentPrompt"> Leave a Comment !</div>
    @using (Ajax.BeginForm("Comments", null, new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "Post",
            OnSuccess = "people.urlmapping.addCommentSuccessfull",
            OnFailure = "people.urlmapping.addCommentFailure"
        }, new {id = "commentForm", @class = "commentForm", name="commentModel"}))
    {
        @Html.Hidden("PostId", Model.PostId)
                
        <div>
            <input type="text" id="commentNamePrompt" name="Name" placeholder="Name (required)"/> 
        </div>
        <div>
            <input type="text" id="commentEmailPrompt" name="Email" placeholder="Email (optional)"/> 
        </div>
        <textarea id="commentBodyInput" class="input-block-level" name="Body" rows="5" placeholder="Enter your comment ..."></textarea>
        //todo : put a cotcha, bot check !
        <div>
            <small id="addCommentErrors" class="text-error"></small>
        </div>
        @ReCaptcha.GetHtml()
        <input type="submit" id="commentSubmitInput" class="btn btn-primary btn-small" ajaxUrl="@Url.Action("Comments","Url")" name="submit" value="Post"/>
        <a id="fakeCommentSubmitInput" class="btn btn-warning btn-small" style="display: none" >
            <i class="icon-upload"></i>
            <span>Posting...</span>
        </a>
    }
</div>

People/Views/Url/Comments.cshtml
@using People.Models
@model DAL.FNhibernate.Entities.Posts


<div id="commentContainer">
    
    <h4> Comments </h4>

    @foreach (var comment in Model.Comments.OrderBy(comments => comments.Samay))
    {
        <div class="comment breadcrumb" id="comment_@comment.Id">
            @*            <div class="commentName">*@
            @if(!string.IsNullOrWhiteSpace(comment.Email))
            {
                <a href="mailto:@comment.Email" class="text-info">@comment.Name</a>
            }
            else
            {
                <b class="text-info"> @comment.Name </b>
            }
            @*            </div>*@
            <span class="commentTime pull-right text-info"> @comment.Samay.ToLongDateString() at @comment.Samay.ToString("HH:mm") </span>

            <div class="commentBody">@Html.Raw(Html.Encode(comment.Body).Replace("\n","<br/>")) </div>

            @if(ViewBag.IsAdminOrOwner?? false)
            {
                <div class="commentControlPanel">
                    <button class="deleteComment btn btn-mini btn-danger" ajaxUrl="@Url.Action("DelteComment","Url",new {@comment.Id})">Delete</button>
                </div>
            }
        </div> 
        <div id="toastMe" class="text-center text-warning"></div>
    }
    @if (Model.Commentable)
    {
        @Html.Partial("AddComment", new CommentsModel{PostId = Model.Id})
    }
    else
    {
        <i>Comments disabled !</i>
    }
</div>

People/Views/Url/Create.cshtml
@model People.Models.PostsViewModel
@{
    ViewBag.Title = "Create Site";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container">
    <div class="hero-unit">
        <h2>Create Site</h2>

        @using (Html.BeginForm("Create", "Url", FormMethod.Post, new { id = "createSiteForm" }))
        {
            <div>
                <input id="subdomain" type="text" class="hero-unit" name="subdomain" value="@Model.Subdomain" data-ajaxurl="@Url.Action("IsDomainFree")"/> 
                <i>@ViewBag.DomainNameWithDot</i> 
                <span id="subdomainAvailability"></span>
            </div>
            @Html.ValidationMessageFor(model => model.Subdomain)
            <div>@Html.ValidationMessage("subDomainChosen",new {@class="text-error"})</div>
            
            <a href="http://imgur.com" target="_blank"><img src="~/Content/img/imgur.png" alt="Imgur" class="pull-right"></a>
            
            <b>Title</b>
            <input type="text" class="input-block-level" name="title" value="@Model.Title"/>  
            @Html.ValidationMessageFor(model => model.Title)
            <br/>
            <div>
                <textarea class="ckeditor" id="body" name="body">@Model.Body</textarea>
            </div>
            @Html.ValidationMessageFor(model => model.Body)
            <br />
            <p>Enable Comments ? 
                <input checked="checked"  id="enableComments" name="commentable" type="checkbox" value="true">
            </p>
            <p>Display Website Hits ? 
                <input id="enableHits" name="ShowHits" type="checkbox" value="true">
            </p>

            @ReCaptcha.GetHtml()
            
            <input id="postSubmitInput" type="submit" class="btn btn-primary" name="submit" value="Publish !"/>
            <a id="fakePostSubmitInput" class="btn btn-warning btn-small" style="display: none" >
                <i class="icon-upload"></i>
                <span>Publishing...</span>
            </a>
        }
    </div>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js" type="text/javascript"></script>
</div>

People/Views/Url/Edit.cshtml
@model People.Models.PostsViewModel

@{
    ViewBag.Title = "Edit Site";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



<div class="container">
    <div class="hero-unit">
        <h2>Edit Site</h2>
        @{ string fullUrl = @Model.Subdomain + ViewBag.DomainNameWithDot; } 
        <h4>@fullUrl</h4>
        @using (Html.BeginForm("Edit", "Url", FormMethod.Post, new{id = "editSiteForm"}))
        {
            @Html.Hidden("id", Model.Id)
            @Html.Hidden("Subdomain", Model.Subdomain)
            <a href="http://imgur.com" target="_blank"><img src="~/Content/img/imgur.png" alt="Imgur" class="pull-right" ></a>
            
            <b>Title</b>
            <input type="text" class="input-block-level" name="title" value="@Model.Title"/>  
            @Html.ValidationMessageFor(model => model.Title)
            <br/>
            <div>
                <textarea name="body" class="ckeditor">@Model.Body</textarea>
            </div>
            @Html.ValidationMessageFor(model => model.Body)
            <br />
            string checkedaa;
            checkedaa = Model.Commentable ? "checked" : "";
            <p>Enable Comments ? 
                <input @checkedaa id="enableComments" name="commentable" type="checkbox" value="true">
            </p>
            <p>Display Website Hits ? 
                <input id="enableHits" name="ShowHits" type="checkbox" value="true">
            </p>
            <input id="postSubmitInput" type="submit" class="btn btn-primary" name="submit" value="Update"/>
            <a id="fakePostSubmitInput" class="btn btn-warning btn-small" style="display: none" >
                <i class="icon-upload"></i>
                <span>Updating...</span>
            </a>
        }
    </div>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js" type="text/javascript"></script>
</div>

People/Views/Url/Iframe.cshtml
@model string

<!DOCTYPE html>

<html>
    <head>
        <title></title>
    </head>
    <body>
        <div>
              @Html.Raw(Model)
        </div>
    </body>
</html>

People/Views/Url/Index.cshtml
@using System.Configuration
@using People.Helpers
@model DAL.FNhibernate.Entities.Posts

@{
    ViewBag.Title = @Model.Title.Chop(20);
    Layout = "~/Views/Shared/_MainUrlLayout.cshtml";
}

<div class="container">
    <br />
    <h3 class="text-center breadcrumb">@Model.Title</h3>
    @if (Model.ShowHits)
    {
        <b class="pull-right">Website Hits: @ViewBag.Hits</b>
    }
    <div class="hero-unit">
        <div class="iframe_body">
            @{
                string domainName = ConfigurationManager.AppSettings["DomanName"];
                string iframeUrl = Url.Action("IframeBody",new {id = Model.Id});
            }
            <iframe id="iframeBody" src="@iframeUrl" frameborder="0" height="100" width="100%" scrolling="no"
                onLoad="people.urlmapping.calcIframeHeight();">
            </iframe>
        </div>
        @if (ViewBag.IsAdminOrOwner ?? false)
        {
            <div class="postControlPanel">
                @Html.ActionLink("Edit","Edit","Url","http",domainName,"",new {id  = Model.Id}, new {@class = "btn btn-primary btn-small "})
            </div>
        }
        @Html.Partial("TwitterFacebookLinks")
        <br/>
        <div class="pull-left small-texty">
            @Html.ActionLink("Create similar page?","Index","Home","http",domainName,"",null, new {})
        </div>
        <br/>
        <hr/>
        @Html.Partial("Comments",Model)
    </div>
</div>

People/Views/Url/PageNotFound.cshtml
@using System.Configuration
@{
    ViewBag.Title = "Page doesnot exist !";
    Layout = "~/Views/Shared/_MainUrlLayout.cshtml";
}

<br />
<div class="container">
    <div class="hero-unit">
        <h2>The page you're looking for doesn't exist !</h2>
        <br/>
        <h3>Create one ?? 
            
            @Html.ActionLink("Yes Please !","Create","Url","http",(string)ViewBag.DomainName,"",null, new {@class = "btn btn-primary btn-large"})
        </h3>        
    </div>
</div>

People/Views/Url/TwitterFacebookLinks.cshtml
<div id="fb-root"></div>
<script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=319369914832518";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-like icon-align-left" data-send="false" data-width="450" data-show-faces="false"></div>

<a href="https://twitter.com/share" class="twitter-share-button pull-right" data-size="large">Tweet</a>
<script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = "//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");</script>